name: Go

on:
  push:
    branches: [ 'main', 'release-*' ]
  pull_request:
    types: [opened, synchronize, reopened]

env:
  FORCE_COLOR: true

jobs:

  build:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version:
          - '1.22'
    steps:
      - uses: awalsh128/cache-apt-pkgs-action@v1
        with:
          packages: gnome-keyring
          version: 0.1.0

      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Workaround for knative.dev/client/pkg/output/tui/progress_test.go#L3-L4
        run: go run ./cmd/k1s setup

      - name: Test
        run: ./mage test

